name: Deploy library

on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Get Release Tag
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Check out master branch
        uses: actions/checkout@v2
        with:
          ref: master

      # Update version.properties file

      - name: Update app version
        run: |
          number_old=$((grep -w VERSION_NUMBER | cut -d= -f2) < livedata-validation/version.properties)
          sed -i "s/VERSION_NUMBER=${number_old}/VERSION_NUMBER=${RELEASE_VERSION}/g" livedata-validation/version.properties

      - name: Commit changes
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Bumb app version to ${RELEASE_VERSION}"

      - name: Setup bintray
        env:
          BINTRAY_USER: ${{ secrets.BINTRAY_USER }}
          BINTRAY_API_KEY: ${{ secrets.BINTRAY_API_KEY }}
        run: |
          echo -e "bintray.user=${BINTRAY_USER}\nbintray.apikey=${BINTRAY_API_KEY}" > local.properties

      # Build and update bintray

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build with Gradle
        run: |
          chmod +x ./gradlew
          ./gradlew bintrayUpload

      # Push version.properties file changes

      - name: Push changes
        run: git push